export class Queues {
  static readonly DATA_PROFILING_REQUEST_QUEUE = process.env.DATA_PROFILING_REQUEST_QUEUE || 'DATA_PROFILING_REQUEST_QUEUE';
  static readonly DATA_PROFILING_RESULT_QUEUE = process.env.DATA_PROFILING_RESULT_QUEUE || 'DATA_PROFILING_RESULT_QUEUE';
  static readonly DATA_ENGINEERING_REQUEST_QUEUE = process.env.DATA_ENGINEERING_REQUEST_QUEUE || 'DATA_ENGINEERING_REQUEST_QUEUE';
  static readonly DATA_ENGINEERING_RESULT_QUEUE = process.env.DATA_ENGINEERING_RESULT_QUEUE || 'DATA_ENGINEERING_RESULT_QUEUE';
  static readonly DATA_SELECTION_REQUEST_QUEUE = process.env.DATA_SELECTION_REQUEST_QUEUE || 'DATA_SELECTION_REQUEST_QUEUE';
  static readonly DATA_SELECTION_RESULT_QUEUE = process.env.DATA_SELECTION_RESULT_QUEUE || 'DATA_SELECTION_RESULT_QUEUE';
  static readonly CLASSICAL_TRAINING_REQUEST_QUEUE = process.env.CLASSICAL_TRAINING_REQUEST_QUEUE || 'CLASSICAL_TRAINING_REQUEST_QUEUE';
  static readonly CLASSICAL_TRAINING_RESULT_QUEUE = process.env.CLASSICAL_TRAINING_RESULT_QUEUE || 'CLASSICAL_TRAINING_RESULT_QUEUE';
  static readonly NAS_TRAINING_REQUEST_QUEUE = process.env.NAS_TRAINING_REQUEST_QUEUE || 'NAS_TRAINING_REQUEST_QUEUE';
  static readonly NAS_TRAINING_RESULT_QUEUE = process.env.NAS_TRAINING_RESULT_QUEUE || 'NAS_TRAINING_RESULT_QUEUE';

  static getAllQueues(): string[] {
    return [
      this.DATA_PROFILING_REQUEST_QUEUE,
      this.DATA_PROFILING_RESULT_QUEUE,
      this.DATA_ENGINEERING_REQUEST_QUEUE,
      this.DATA_ENGINEERING_RESULT_QUEUE,
      this.DATA_SELECTION_REQUEST_QUEUE,
      this.DATA_SELECTION_RESULT_QUEUE,
      this.CLASSICAL_TRAINING_REQUEST_QUEUE,
      this.CLASSICAL_TRAINING_RESULT_QUEUE,
      this.NAS_TRAINING_REQUEST_QUEUE,
      this.NAS_TRAINING_RESULT_QUEUE,
    ];
  }
}