# Base image
FROM node:22

# Create app directory
WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the source code
COPY . .

# Expose the app port
EXPOSE 3001

# Use a development command (assumes you have a script like "start:dev")
CMD ["npm", "run", "start:dev"]
